[package]
name = "teloxide_mvp"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
teloxide = { version = "0.12.2", features = ["macros"] }
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros", "rt"] }
